Hinzufügen der Option verschieden Preistypen zu nutzen
symcon/Betriebsstundenzaehler pull request #10
Opened 2022-08-01 14:16 UTC by Sunnyka98

Mit der Option kann der Nutzer entscheiden ob der Preis fest eingestellt sein oder mit eine geloggt Variable dynamisch berechnet werden soll. 

close https://github.com/symcon/modules/issues/227

2022-08-01 18:37 UTC, paresy requested changes
Ein paar Kommentare :-)

2022-08-01 18:37 UTC, paresy commented on Betriebsstundenzaehler/README.md
> +
Die können raus. Die sind ja nicht für den Nutzer relevant. Trotzdem cool, dass du Dokumentation ernst nimmst!

2022-08-01 18:37 UTC, paresy commented on Betriebsstundenzaehler/module.php
> +        $form = json_decode(file_get_contents('form.json', true), true);
https://github.com/symcon/SymconTest/blob/ec1483eb7da7631532a4f950c9bdb2bca23891f8/ListAction/module.php#L17 So machen wir das normalerweise. Ist wahrscheinlich genauso gut; Für die Konsistenz wäre es gut, dies anzupassen.

2022-08-01 18:37 UTC, paresy commented on Betriebsstundenzaehler/module.php
> +        if ($status == 'Static') {
Das kann man viel schöner und kürzer machen. z.B.
```
$this->UpdateFormField('Price', 'visible', $status == 'Static');
$this->UpdateFormField('PriceDynamic', 'visible',  $status == 'Dynamic');
```

2022-08-01 18:37 UTC, paresy commented on Betriebsstundenzaehler/module.php
> +    public function FormCalculateCost(bool $calculate)
siehe oben die kürzere Variante

2022-08-01 18:37 UTC, paresy commented on Betriebsstundenzaehler/module.php
> +            if ($this->ReadPropertyString('PriceType') == 'Static') {
Vielleicht ein switch case? Dann kann man sich den Kommentar beim "else" sparen. (Definitiv gut, dass du den Kommentar gesetzt hast)

2022-08-01 18:37 UTC, paresy commented on Betriebsstundenzaehler/module.php
> +                $this->SetValue('CostLastPeriod', $getHours($startTimeLastPeriod, $startTimeThisPeriod) * $this->ReadPropertyFloat('Price') / 100);
Warum diese -1 Änderung? Und hier ist der Preis immer Statisch?

2022-08-01 18:37 UTC, paresy commented on Betriebsstundenzaehler/module.php
> +            $values = AC_GetAggregatedValues($archiveID, $this->ReadPropertyInteger('Source'), $aggregationLevel, $startTime, $endTime, 0);
Diese Zeile ist irgendwie doppelt. Die ist paar Zeilen weiter oben ebenfalls schon drin?

2022-08-02 09:50 UTC, Sunnyka98 commented on Betriebsstundenzaehler/module.php
> +            $values = AC_GetAggregatedValues($archiveID, $this->ReadPropertyInteger('Source'), $aggregationLevel, $startTime, $endTime, 0);
Wie besprochen, sind zwei verscheiden Berechnungen

2022-08-26 09:29 UTC, merged