fixed error occurring if instance is loader before archive (PHP-147)
symcon/Betriebsstundenzaehler pull request #2
Opened 2020-09-03 14:08 UTC by TillBrede

2020-09-03 14:57 UTC, DrNiels requested changes

2020-09-03 14:57 UTC, DrNiels commented on Betriebsstundenzaehler/module.php
> +}
Kann es sein, dass du deine Commits nicht durchschaust oder wieso hast du das neue Zeilenende mit comittet?

2020-09-03 14:57 UTC, DrNiels commented on Betriebsstundenzaehler/module.php
> +        if ($this->ReadPropertyBoolean('Active') && $this->GetTimerInterval('UpdateCalculationTimer') < ($this->ReadPropertyInteger('Interval') * 1000 * 60)) {
Wenn der Code hier ankommt, ist Active nicht zwangsweise true? Da kann man noch was optimieren

2020-09-03 14:57 UTC, DrNiels commented on Betriebsstundenzaehler/module.php
> -        $this->Calculate();
Ist das $this->Calculate() mittlerweile verschwunden? Denn das steckt scheinbar nicht in setupInstance()

2020-09-04 07:16 UTC, TillBrede commented on Betriebsstundenzaehler/module.php
> +}
wurde schon mit dem 'fixed style' commit behoben

2020-09-04 14:38 UTC, DrNiels commented on Betriebsstundenzaehler/module.php
> +        if ($this->ReadPropertyBoolean('Active') && $this->GetTimerInterval('UpdateCalculationTimer') < ($this->ReadPropertyInteger('Interval') * 1000 * 60)) {
Schau dir die Stelle gerne noch einmal genauer an, da geht noch mehr

2020-09-04 14:39 UTC, DrNiels requested changes
Beim Active-Check geht noch mehr

2020-09-07 09:29 UTC, DrNiels approved these changes

2020-10-06 12:43 UTC, DrNiels approved these changes

2020-10-06 12:44 UTC, merged